### ISSUE TITLE
[QUESITION] Feature Comparision?

### ISSUE THREAD

**Issue by dalisoft** [dalisoft/animo.js#3]
What is best:
* Performance (Higher performance with limited feature)
* or
* Flexible (More features with some performance down)

**Comment by thednp** [comment]
Obviously there is no way to ONLY pick one of them, there has to be an acceptable combination of the two, but I don't think the two counter each other that much.

**Comment by dalisoft** [comment]
If i select performance, need delete features functions and this boosts performance over 25%!
If i select more flexible feature like SVG, Attr, Data-Attr, etc, this using more memory and uses sub-function and performance dropping by these features! Or i can make two version? Users can download by own animation type

**Comment by thednp** [comment]
You can use both in a way to keep performance while having flexibility. Again it's not that they counter each other, it's about making animo usable and this can be done.

**Comment by dalisoft** [comment]
Thanks! I try make better animation engine with combining both feature/performance! (y)
